export const FETCH_PEOPLE_REQUEST = "FETCH_PEOPLE_REQUEST";
export const FETCH_PEOPLE_FAILURE = "FETCH_PEOPLE_FAILURE";
export const FETCH_PEOPLE_SUCCESS = "FETCH_PEOPLE_SUCCESS";
export const RECEIVE_PEOPLE = "RECEIVE_PEOPLE";
